name: Daily Data Fetch

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          
      - name: Fetch data
        env:
          API_KEY: ${{ secrets.BUNDESTAG_API_KEY }}
          BASE_URL: "https://search.dip.bundestag.de/api/v1"
          DATABASE_URL: "sqlite:///bundestag.db"
        run: python src/data/fetch_daily.py
        
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          #git add bundestag.db
          git add -f bundestag.db  # -f Flag zum Forcieren des Adds
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data $(date '+%Y-%m-%d')"
          git push